#computers
services:
  db-computer:
    # 실행이 잘 안될경우
    # platform: linux/86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 3306:3306

  server-computer: #computer name
    build:
      context: . #path
      dockerfile: dockerFile.graphql #file name
    # .env 파일을 대치시켜줌
    env_file:
      - ./.env
    ports:
      - 3000:3000 #port forwarding
    volumes:
      - ./src:/techHub/src
